language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "io.js"
before_install:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
deploy:
  - provider: npm
    skip_cleanup: true
    email: "hello@dominykas.com"
    api_key:
      secure: "bFDv3DqM4Q5Ilz5E4k3wcgAnNhjEusQqSMpGLN0+O27bIr4xYRM7TrOP64r4dtWrxtWtr+0pDWZjyDj6NHCVHUm4gmf6yxYQVx/M81Goz6BNyWouv1UKrikbLqfZQ8wDfZyX/NKGG1tSfeJoIHrmbHSUZqXECRjDk0fuzYh2sqM="
    on:
      tags: true
      node_js: "io.js"
