language: node_js
sudo: false
node_js:
  - "4"
  - "6"
before_install:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - npm i -g npm
deploy:
  - provider: npm
    skip_cleanup: true
    email: "hello@dominykas.com"
    api_key:
      secure: "crgqTFxY8eQ3QxYhDFJziWpcWnaqvspZFPzTotTwko+3DiyOBgecc3WdAgtRyg8eH6fyCxmoh9+uyv6zbeTtTR3/0wgVeZfyXwDo2loAeyZ3EzKF0QCE23oC+9eER0emnt1mNmdl4NatunAtbfCjFmCmCvd7Z7+Rqlw/2Pnif7k="
    on:
      tags: true
      node_js: "6"
